on: [push]
name: Build image, push to ACR, and deploy to Container Apps

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main

        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

        # - name: 'Build and push image'
        #   uses: azure/docker-login@v1
        #   with:
        #     login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        #     username: ${{ secrets.REGISTRY_USERNAME }}
        #     password: ${{ secrets.REGISTRY_PASSWORD }}
        # - run: |
        #     docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/elsa:latest
        #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/elsa:latest

        - name: 'Deploy Container App'
          uses: azure/container-apps-deploy-action@v1
          with:
            appSourcePath: ${{ github.workspace }}
            acrName: elsaregistry
            containerAppName: elsa
            resourceGroup: elsa-resource-group
            environmentVariables: BOT_TOKEN=${{ secrets.BOT_TOKEN }}
